video_new:
    path:   /new
    defaults:   { _controller: "AppBundle:Video:new"}
    methods:    POST
    
video_edit:
    path:   /edit/{video_id}
    defaults:   { _controller: "AppBundle:Video:edit", video_id:null }
    methods:    POST    
    
video_uploadimage:
    path:   /upload-image/{video_id}
    defaults:   { _controller: "AppBundle:Video:upload", video_id:null }
    methods:    POST    
    
video_uploadvideo:
    path:   /upload-video/{video_id}
    defaults:   { _controller: "AppBundle:Video:upload", video_id:null }
    methods:    POST    
    
video_list:
    path:   /list
    defaults:   { _controller: "AppBundle:Video:videos" }
    methods:    GET       
    
video_lasts_videos:
    path:   /lasts-videos
    defaults:   { _controller: "AppBundle:Video:lastsVideos" }
    methods:    GET    
    
video_detail:
    path:   /detail/{id}
    defaults:   { _controller: "AppBundle:Video:video", id:null }
    methods: GET